name: app_apiv2
channels:
  - conda-forge
  - defaults
dependencies:
  # core
  - python=3.12
  - pip
  - setuptools

  # scientific / GW
  - numpy<2.0                     # safeguard until GW packages transition to NumPy 2.0
  - scipy
  - gwpy<4.0                      # precautionary pin for latest GWPy release
  - gwosc=0.8.1
  - python-framel                 # GWF file format support
  - python-ldas-tools-framecpp    # GWF file format support

  # development only
  - pyinstaller>=6.7

  # GUI
  - pip:
      - pyqt6==6.7.1    
