name: app_upd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2.0 # safeguard until GW packages transition to NumPy 2.0
  - pip
  - setuptools
  # basic GW packages needed
  - gwpy=3.0.11
  - gwosc=0.8.1
  # packages needed for reading/writing to GWF format
  - python-framel
  - python-ldas-tools-framecpp
  - python-ldas-tools-al
  # package for binary creation (development only)
  - pyinstaller>=6.7
  - pip:
      - pyqt6==6.7.1    
